<!DOCTYPE html>
<html lang="pt-BR" itemid="<!--#echo var='url' -->" itemtype="http://schema.org/NewsArticle" itemscope="" xmlns:og="http://opengraphprotocol.org/schema/">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!--#include file="head__embed_head.inc"-->
</head>

<body class="f-graphic">
	<div class="folha-loader">
		<div class="folha-loader__container">
			<img src="/library/folhastyle/3.0/images/loading.gif" alt="Imagem de carregamento">
		</div>
	</div>
