<!-- AUDIENCIA-TOPO -->
<!--#if expr="$HTTP_HOST != /staging/"-->
<script id="navegg" src="//tag.navdmp.com/tm23947.js"></script>
<!-- ChartBeat  -->
<script>
	var _sf_async_config = _sf_async_config || {};
	/** CONFIGURATION START **/
	_sf_async_config.uid = 50059;
	_sf_async_config.domain = 'folha.com.br';
	_sf_async_config.topStorageDomain = 'uol.com.br';
	_sf_async_config.flickerControl = false;
	_sf_async_config.useCanonical = true;
	/** CONFIGURATION END **/
	var _sf_startpt = (new Date()).getTime();
</script>
<script src="//static.chartbeat.com/js/chartbeat_mab.js"></script>
<!--//ChartBeat -->
<!--#endif-->
<!-- FIM AUDIENCIA-TOPO -->
