const postcss = require('gulp-postcss');
const gulp = require('gulp');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const cssmqpacker = require('css-mqpacker');
const htmlmin = require('gulp-html-minifier');
const babel = require('gulp-babel');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const stylus = require('gulp-stylus');


const HTML_MINIFY = {
	collapseWhitespace: true,
	includeAutoGeneratedTags: false,
};

const PLUGIN_CSS = [
	autoprefixer(),
	// autoprefixer({
	// 	browsers: ['last 4 versions', '> 1%'],
	// }),
	cssmqpacker(),
	cssnano(),
];

gulp.task('js:includes:full', () => gulp.src('./src/templates/includes/virtual/3.0/arte/article_full-page_script.js')
	.pipe(babel())
	.pipe(concat('article_full-page_script.js'))
	.pipe(uglify())
	.pipe(gulp.dest('./build/virtual/3.0/arte/')));

gulp.task('js:includes', () => gulp.src([
	'./src/templates/includes/virtual/3.0/arte/**/*.js',
])
	.pipe(babel())
	.pipe(uglify())
	.pipe(gulp.dest('./build/virtual/3.0/arte/')));

gulp.task('stylus', () => gulp.src('./src/assets/style/**/*.styl')
	.pipe(stylus())
	.pipe(gulp.dest('./build/style/')));

gulp.task('css:includes', () => gulp.src('./src/templates/includes/virtual/3.0/arte/**/*.css')
	.pipe(postcss(PLUGIN_CSS))
	.pipe(gulp.dest('./build/virtual/3.0/arte/')));

gulp.task('html:includes', () => gulp.src('./src/templates/includes/virtual/3.0/arte/**/*.inc')
	.pipe(htmlmin(HTML_MINIFY))
	.pipe(gulp.dest('./build/virtual/3.0/arte/')));

gulp.task('html:includes:paywall', () => gulp.src('./node_modules/paywall.js/dist/paywall.inc')
	.pipe(gulp.dest('./src/templates/includes/virtual/3.0/arte/')));

gulp.task('build', ['css:includes', 'html:includes', 'js:includes', 'js:includes:full', 'stylus']);
